name: learn_dart_lib
description: This is just for testing package.
version: 1.0.1
homepage: https://www.wadaw.id
repository: https://github.com/havus/learn_dart_lib

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
